# Generated by Django 3.2.20 on 2023-12-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='translater.lesson'),
        ),
    ]
