# Generated by Django 5.0 on 2023-12-22 17:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translater', '0002_alter_test_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='user_translation',
        ),
        migrations.AddField(
            model_name='testquestion',
            name='corect_answer',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translater.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
